### ISSUE TITLE
Mettre à jour la liste des membres du bureau

### ISSUE THREAD

**Issue by yaf** [AgileFrance/AgileFrance.github.io#1]
Bonjour,

Il me semble qu'il y a un nouveau bureau, et je vois que sur le site, c'est toujours le précédent qui est mentionné.

**Comment by MattiSG** [comment]
Tout à fait, merci @yaf ! Je termine de refactor le site actuel et on va se mettre aux changements de contenu 😄 

Comme indiqué dans #2 :

> Désolé pour le délai de traitement, je n'ai que récemment obtenu les droits sur l'organisation. Comme tu peux le voir je viens de mettre de l'ordre dans les métadonnées de l'organisation (et dans ses membres et anciens dépôts). Nous allons reprendre progressivement en main tout cela 🙂
