### ISSUE TITLE
Mettre à jour l'adresse postale

### ISSUE THREAD

**Issue by yaf** [AgileFrance/AgileFrance.github.io#2]
Bonjour,

Il me semble que l'adresse postale est mainteannt 14 avenue ledru-rollin 75012 Paris. Est-ce que mon information n'est pas bonne ?

**Comment by MattiSG** [comment]
Tout à fait, merci @yaf ! N'hésite pas à ouvrir une PR si tu le souhaites 😄

Désolé pour le délai de traitement, je n'ai que récemment obtenu les droits sur l'organisation. Comme tu peux le voir je viens de mettre de l'ordre dans les métadonnées de l'organisation (et dans ses membres et anciens dépôts). Nous allons reprendre progressivement en main tout cela 🙂

**Comment by MattiSG** [comment]
@davidbgk si ça te dit de t'en charger avec un passage à du HTML sémantique au passage, après avoir revu et mergé #3 pendant mon sommeil, n'hésite pas 😄 — idem pour #1.

**Comment by MattiSG** [comment]
@yaf pourrais-tu nous confirmer qu'il y a bien un sticker « Agile France » sur la boîte aux lettres d'/ut7 ? 😅

**Comment by yaf** [comment]
Il n'y a pas de sticker sur la boite aux lettres, parce que nous n'avons pas de boite aux lettres. Par contre le gardien (qui est celui qui reçoit et distribue le courrier) sais que Agile France c'est chez nous.  Je pourrais faire une vérification de routine en lui demandant dans la semaine. Nous avons une pochette inbox agile france avec le courrier pour l'asso dedans.

**Comment by MattiSG** [comment]
Top, merci @yaf ! :)
