### ISSUE TITLE
Faire un lien vers la profession de foi

### ISSUE THREAD

**Issue by davidbgk** [AgileFrance/AgileFrance.github.io#7]
https://mattischneider.fr/agile/france/2018

Ou conserver une copie directement sur le site pour remplacer l'actuelle `intention_bureau.html`?

**Comment by MattiSG** [comment]
Je trouverai intéressant de toutes les archiver sur ce site, ne serait-ce que comme cache 😉 

Il y a aussi https://sites.google.com/site/emmanuelgaillot/nouvellevague, plus un mail sur la Nouvelle Vague Redux.

**Comment by davidbgk** [comment]
+1 pour l'archivage accessible (vs. git)
